### ISSUE TITLE
Why not use OpenPolicyAgent

### ISSUE THREAD

**Issue by ekarlso** [octarinesec/MAPL#1]
Hi, why are you not using REPL / OPA?

**Comment by edodekel** [comment]
Hi,
Looking at the problem of access control as a specific use-case of evaluating logical expression, while mathematically valid is not necessarily practical nor intuitive. 
In MAPL we put usability ahead of coverage. We want to easily read and understand a policy rule.
What we have observed is that most access control rules have a similar structure: If I want to allow User X to access resource Y, I want to have a language where the rule is as simple as that statement.
That is not the case with OPA, REPL and several other languages we evaluated. 
AWS IAM, k8s network policy and Istio authorization are closer but they each use a different language.
